import Head from "next/head";
import { PerksLayout } from "../../components/PerksLayout";

const RedeemPage = () => {
  return (
    <>
      <Head>
        <title>Partners - B3NZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PerksLayout>awe</PerksLayout>
    </>
  );
};

export default RedeemPage;
