import Head from "next/head";
import Link from "next/link";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

interface BlogProps {
  posts: {
    frontMatter: any;
    slug: string;
  }[];
}

const styles = {
  container: "py-10",
  contentContainer: "max-w-[1400px] mx-auto",
  headerContainer: "text-center",
  title: "text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl",
  description: "mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4",
  gridContainer: "p-5 mt-20 mx-auto grid gap-5 lg:grid-cols-3",
  postContainer:
    "flex flex-col rounded-lg shadow-sm border-[1px] overflow-hidden cursor-pointer",
  postImageContainer: "flex-shrink-0",
  postImage: "h-48 w-full object-cover",
  postBody: "flex-1 bg-white p-6 flex flex-col justify-between",
  postInfoContainer: "flex-1 block mt-2",
  postTitle: "text-xl font-semibold text-gray-900",
  postDescription: "mt-3 text-base text-gray-500",
  postAuthorContainer: "mt-6 flex items-center",
  postAuthorImageContainer: "flex-shrink-0",
  postAuthorImage: "h-10 w-10 rounded-full",
  postAuthorInfoContainer: "ml-3",
  postAuthorName: "text-sm font-medium text-gray-900",
  postDateContainer: "flex space-x-1 text-sm text-gray-500",
};

const Blog: React.FC<BlogProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>B3NZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.contentContainer}>
          <div className={styles.headerContainer}>
            <h2 className={styles.title}>From the blog</h2>
            <p className={styles.description}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa
              libero labore natus atque, ducimus sed.
            </p>
          </div>
          <div className={styles.gridContainer}>
            {posts.map((post: any) => (
              <Link
                href={"/blog/" + post.slug}
                passHref
                key={post.frontMatter.title}
              >
                <div key={post.title} className={styles.postContainer}>
                  <div className={styles.postImageContainer}>
                    <img
                      className={styles.postImage}
                      src={post.frontMatter.thumbnailUrl}
                      alt=""
                    />
                  </div>
                  <div className={styles.postBody}>
                    <div className={styles.postInfoContainer}>
                      <p className={styles.postTitle}>
                        {post.frontMatter.title}
                      </p>
                      <p className={styles.postDescription}>
                        {post.frontMatter.description}
                      </p>
                    </div>
                    <div className={styles.postAuthorContainer}>
                      <div className={styles.postAuthorImageContainer}>
                        <a>
                          <span className="sr-only">
                            {post.frontMatter.authorName}
                          </span>
                          <img
                            className={styles.postAuthorImage}
                            src={post.frontMatter.authorImage}
                            alt=""
                          />
                        </a>
                      </div>
                      <div className={styles.postAuthorInfoContainer}>
                        <p className={styles.postAuthorName}>
                          {post.frontMatter.authorName}
                        </p>
                        <div className={styles.postDateContainer}>
                          <time dateTime={post.frontMatter.datetime}>
                            {post.frontMatter.date}
                          </time>
                          <span aria-hidden="true">&middot;</span>
                          <span>{post.frontMatter.readingTime} read</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Blog;

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join("posts"));
  const posts = files.map((filename) => {
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data: frontMatter } = matter(markdownWithMeta);
    return {
      frontMatter,
      slug: filename.split(".")[0],
    };
  });
  return {
    props: {
      posts,
    },
  };
};
